# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cffc905ffa304e42445f66f153b9cc6e8f4d33ef01c961aac6cb30b0b0e01b36e6c963fca7f4fc6746a0c56cd7e0f826ff1fc3018bb7fe97836599522c8342cf

test:
  secret_key_base: f2cc02d6c18ba32f0dc20dc29789997e171688671211ecc83de299529d02ce01d5ef8cc958257135234717fccc87ea4fba65dcc7ca2f09407a037bd1ab810be3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
